/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallervectores;

import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ejercicio1 extends javax.swing.JFrame {

    int v[];

    /**
     * Creates new form Ejercicio1
     */
    public Ejercicio1() {
        initComponents();
        cmdLlenar.setEnabled(false);
        cmdAutoLlenado.setEnabled(false);
        cmdMostrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdLlenar = new javax.swing.JButton();
        cmdAutoLlenado = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        df = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSumatoria = new javax.swing.JTextField();
        txtProductoria = new javax.swing.JTextField();
        txtMayor = new javax.swing.JTextField();
        txtMenor = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        cmdLlenar.setText("Llenar");
        cmdLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 90, 90, -1));

        cmdAutoLlenado.setText("A.Llenado");
        cmdAutoLlenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutoLlenadoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAutoLlenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, -1));

        cmdBorrar.setText("borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 110, 210));

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        df.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        df.setText("Longitud");
        df.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.add(df, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        txtLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudActionPerformed(evt);
            }
        });
        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel4.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 60, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 160, 70));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Resultado");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, 20));

        jLabel3.setText("Sumatoria");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel4.setText("Productoria");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel5.setText("Mayor");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setText("Menor");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtSumatoria.setEditable(false);
        jPanel5.add(txtSumatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 60, -1));

        txtProductoria.setEditable(false);
        txtProductoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductoriaActionPerformed(evt);
            }
        });
        jPanel5.add(txtProductoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 60, -1));

        txtMayor.setEditable(false);
        jPanel5.add(txtMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 60, -1));

        txtMenor.setEditable(false);
        jPanel5.add(txtMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 60, -1));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 160, 140));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAutoLlenadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutoLlenadoActionPerformed
        int n;
        for (int i = 0; i < v.length; i++) {
            n = (int) (Math.random() * 25 + 1);
            v[i] = n;
            cmdCrear.setEnabled(false);
            cmdAutoLlenado.setEnabled(true);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(true);
            cmdBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdAutoLlenadoActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        int sumatoria, Mayor = 0, menor;
        int acum = 0, produc = 1;
        for (int i = 0; i < v.length; i++) {
            acum = acum + v[i];
            produc = produc * v[i];
            menor = v[0];
            if (v[i] < menor) {
                menor = v[i];

            } else if (v[i] > Mayor) {
                Mayor = v[i];

            } else {

            }
            txtSumatoria.setText(String.valueOf(acum));
            txtProductoria.setText(String.valueOf(produc));
            txtMayor.setText(String.valueOf(Mayor));
            txtMenor.setText(String.valueOf(menor));
            cmdCrear.setEnabled(false);
            cmdAutoLlenado.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(false);
            cmdBorrar.setEnabled(true);
        }
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int longitud;
        if(txtLongitud.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Digite la longitud", "Error", JOptionPane.ERROR_MESSAGE);
           txtLongitud.requestFocusInWindow();
           cmdCrear.setEnabled(true);
           cmdLlenar.setEnabled(false);
           cmdAutoLlenado.setEnabled(false);
           cmdMostrar.setEnabled(false);
       }else if(txtLongitud.getText().trim().equals("0")){
           JOptionPane.showMessageDialog(this, "La longitud debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
           txtLongitud.requestFocusInWindow();
           txtLongitud.selectAll();
           cmdCrear.setEnabled(true);
           cmdLlenar.setEnabled(false);
           cmdAutoLlenado.setEnabled(false);
           cmdMostrar.setEnabled(false);
       }else{
           longitud=Integer.parseInt(txtLongitud.getText());
           v = new int[longitud];
           JOptionPane.showMessageDialog(this, "Vector creado satisfactoriamente");
           txtLongitud.setEditable(false);
            cmdCrear.setEnabled(false);
        cmdAutoLlenado.setEnabled(true);
        cmdLlenar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(true);
       }
       
    
        

    }//GEN-LAST:event_cmdCrearActionPerformed
    
        
     


    private void cmdLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarActionPerformed
        int n;

        for (int i = 0; i < v.length; i++) {

            n = Integer.valueOf(JOptionPane.showInputDialog("Digite el elemento en la posición " + i));

            v[i] = n;
            cmdCrear.setEnabled(false);
            cmdAutoLlenado.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(true);
            cmdBorrar.setEnabled(true);
            

        }
    }//GEN-LAST:event_cmdLlenarActionPerformed

    private void txtProductoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductoriaActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtLongitud.setText("");
        txtSumatoria.setText("");
        txtProductoria.setText("");
        txtMenor.setText("");
        txtMayor.setText("");
        txtLongitud.requestFocusInWindow();
        v = null;
        txtLongitud.setEditable(true);
        cmdCrear.setEnabled(true);
        cmdAutoLlenado.setEnabled(false);
        cmdLlenar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdBorrar.setEnabled(true);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudActionPerformed
    
        
    }//GEN-LAST:event_txtLongitudActionPerformed
    
    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
        
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtLongitudKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAutoLlenado;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JLabel df;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtMayor;
    private javax.swing.JTextField txtMenor;
    private javax.swing.JTextField txtProductoria;
    private javax.swing.JTextField txtSumatoria;
    // End of variables declaration//GEN-END:variables
}
