/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallervectores;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Ejercicio2 extends javax.swing.JFrame {
 
    int v[];
    /**
     * Creates new form Ejercicio2
     */
    public Ejercicio2() {
        initComponents();
        
        cmdAuto.setEnabled(false);
        cmdLlenar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        cmdLlenar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdReset = new javax.swing.JButton();
        cmdAuto = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        df = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPrimos = new javax.swing.JTextField();
        txtImpares = new javax.swing.JTextField();
        txtPares = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 11, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 200));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdLlenar.setText("Llenar");
        cmdLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });
        jPanel5.add(cmdReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, -1));

        cmdAuto.setText("A.llenar");
        cmdAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutoActionPerformed(evt);
            }
        });
        jPanel5.add(cmdAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel5.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 90, 210));

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        df.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        df.setText("Longitud");
        df.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel6.add(df, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 50));

        txtLongitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLongitudActionPerformed(evt);
            }
        });
        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel6.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 60, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 220, 80));

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Cantidad de primos");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel3.setText("Cantidad de impares");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel1.setText("Cantidad de pares");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtPrimos.setEditable(false);
        jPanel7.add(txtPrimos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, -1));

        txtImpares.setEditable(false);
        jPanel7.add(txtImpares, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 60, -1));

        txtPares.setEditable(false);
        jPanel7.add(txtPares, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 60, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 220, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLongitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLongitudActionPerformed

    }//GEN-LAST:event_txtLongitudActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int longitud;
        if(txtLongitud.getText().trim().isEmpty()){
           JOptionPane.showMessageDialog(this, "Digite la longitud", "Error", JOptionPane.ERROR_MESSAGE);
           txtLongitud.requestFocusInWindow();
       }else if(txtLongitud.getText().trim().equals("0")){
           JOptionPane.showMessageDialog(this, "La longitud debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
           txtLongitud.requestFocusInWindow();
           txtLongitud.selectAll();
       }else{
           longitud=Integer.parseInt(txtLongitud.getText());
           v = new int[longitud];
           JOptionPane.showMessageDialog(this, "Vector creado satisfactoriamente");
           txtLongitud.setEditable(false);
            cmdCrear.setEnabled(false);
        cmdAuto.setEnabled(true);
        cmdLlenar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdReset.setEnabled(true);
       }
       
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutoActionPerformed
        int n;
        for (int i = 0; i < v.length; i++) {
            n = (int) (Math.random() * 25 + 1);
            v[i] = n;
        }cmdCrear.setEnabled(false);
            cmdAuto.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(true);
            cmdReset.setEnabled(true);
        
               
           
    }//GEN-LAST:event_cmdAutoActionPerformed
       
    private void cmdLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarActionPerformed
       int n;

        for (int i = 0; i < v.length; i++) {

            n = Integer.valueOf(JOptionPane.showInputDialog("Digite el elemento en la posición " + i));

    

            v[i] = n;
        }cmdCrear.setEnabled(false);
            cmdAuto.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(true);
            cmdReset.setEnabled(true);
            
    }//GEN-LAST:event_cmdLlenarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        int acum=0,acum2=0;
        double contador=0,contador2=0;
        boolean primo=true;
         for (int i = 0; i < v.length; i++){
        if(v[i]%2==0){
                 acum=acum+1;
                 
             }else if(v[i]%2==1){
                 acum2=acum2+1;
             }
        
         }
        for (int j = 0; j < v.length; j++) {
                 if(v[j]%contador==0){
                     primo=false;
                 }else{
                     contador2=contador2+1;
                 }
        }
             
        
                
        txtPrimos.setText(String.valueOf(contador2));
             
         
             
             
         
         txtPares.setText(String.valueOf(acum));
         txtImpares.setText(String.valueOf(acum2));
         
         cmdCrear.setEnabled(false);
         cmdAuto.setEnabled(false);
         cmdLlenar.setEnabled(false);
         cmdMostrar.setEnabled(false);
         cmdReset.setEnabled(true);
        
             
           
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
        txtLongitud.setText("");
        txtPares.setText("");
        txtImpares.setText("");
        txtPrimos.setText("");
        txtLongitud.requestFocusInWindow();
        txtLongitud.setEditable(true);
        v=null;
        cmdCrear.setEnabled(true);
        cmdAuto.setEnabled(false);
        cmdLlenar.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdReset.setEnabled(true);
        
    }//GEN-LAST:event_cmdResetActionPerformed

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
 char c=evt.getKeyChar();
        if(!Character.isDigit(c)){
            getToolkit().beep();
            evt.consume();
        }        
    }//GEN-LAST:event_txtLongitudKeyTyped
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAuto;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdReset;
    private javax.swing.JLabel df;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtImpares;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextField txtPares;
    private javax.swing.JTextField txtPrimos;
    // End of variables declaration//GEN-END:variables
}
