/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tallervectores;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Punto3 extends javax.swing.JFrame {
double v[];
double r[];
double v1[];
    /**
     * Creates new form Punto3
     */
    public Punto3() {
        initComponents();
        cmdLlenar.setEnabled(false);
        cmdAuto.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdResta.setEnabled(false);
        cmdSuma.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmdReset = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdResta = new javax.swing.JButton();
        cmdSuma = new javax.swing.JButton();
        cmdAuto = new javax.swing.JButton();
        cmdLlenar = new javax.swing.JButton();
        txtLongitud = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtVector = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtVector1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtVectorR = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel1.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel1.setText("Longitud");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdReset.setText("Reset");
        cmdReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdResetActionPerformed(evt);
            }
        });
        jPanel2.add(cmdReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 70, -1));

        cmdResta.setText("Resta");
        cmdResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRestaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        cmdSuma.setText("Sumar");
        cmdSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSumaActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        cmdAuto.setText("Auto");
        cmdAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        cmdLlenar.setText("Llenar");
        cmdLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdLlenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 130, 420));
        jPanel1.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 90, 30));

        jLabel2.setText("Operaciones");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        txtVector.setColumns(20);
        txtVector.setRows(5);
        jScrollPane1.setViewportView(txtVector);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        txtVector1.setColumns(20);
        txtVector1.setRows(5);
        jScrollPane2.setViewportView(txtVector1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        txtVectorR.setColumns(20);
        txtVectorR.setRows(5);
        jScrollPane3.setViewportView(txtVectorR);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
       int longitud;
        if(txtLongitud.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la longitud", "Error", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
            cmdCrear.setEnabled(true);
            cmdLlenar.setEnabled(false);
            cmdAuto.setEnabled(false);
            cmdMostrar.setEnabled(false);
        }else if(txtLongitud.getText().trim().equals("0")){
            JOptionPane.showMessageDialog(this, "La longitud debe ser mayor que cero", "Error", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
            txtLongitud.selectAll();
        }else{
            longitud=Integer.parseInt(txtLongitud.getText());
            v= new double[longitud];
            v1= new double[longitud];
            r= new double [longitud];
            txtLongitud.setEditable(false);
           
        }
        cmdCrear.setEnabled(false);
        cmdAuto.setEnabled(true);
        cmdLlenar.setEnabled(true);
        cmdMostrar.setEnabled(false);
        cmdReset.setEnabled(true);
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarActionPerformed
        double n;
        for (int i = 0; i < v.length; i++) {
            n= Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento en la posición " + i));
            v[i]=n;
        }
        for (int i = 0; i < v.length; i++) {
            n= Double.parseDouble(JOptionPane.showInputDialog("Digite el elemento en la posición " + i));
            v1[i]=n;
        }
        cmdCrear.setEnabled(false);
            cmdAuto.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(true);
            cmdReset.setEnabled(true);
            cmdResta.setEnabled(true);
            cmdSuma.setEnabled(true);
    }//GEN-LAST:event_cmdLlenarActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
        for (int i = 0; i < v.length; i++) {
            txtVector.append(""+v[i]+"\n");
            
        }
        for (int i = 0; i < v.length; i++) {
            txtVector1.append(""+v1[i]+"\n");
            
        }
        cmdCrear.setEnabled(false);
            cmdAuto.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(false);
            cmdReset.setEnabled(true);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdResetActionPerformed
       txtVector.setText("");
       txtLongitud.setText("");
       txtVector1.setText("");
       txtVectorR.setText("");
       txtLongitud.requestFocusInWindow();
       v=null;
       v1=null;
       
    }//GEN-LAST:event_cmdResetActionPerformed

    private void cmdAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutoActionPerformed
       double n,m;
        for (int i = 0; i < v.length; i++) {
            n= (int) (Math.random()*25+1);
            v[i]=n;
            
        }for (int i = 0; i < v.length; i++) {
            m= (int) (Math.random()*25+1);
            v1[i]=m;
            
        }
        
        cmdCrear.setEnabled(false);
        cmdAuto.setEnabled(false);
        cmdLlenar.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdReset.setEnabled(true);
        cmdResta.setEnabled(true);
        cmdSuma.setEnabled(true);
    }//GEN-LAST:event_cmdAutoActionPerformed

    private void cmdSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSumaActionPerformed
        for (int i = 0; i < v.length; i++) {
            r[i]=v[i]+v1[i];
            txtVectorR.append(r[i]+"\n");
            cmdCrear.setEnabled(false);
            cmdAuto.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(true);
            cmdReset.setEnabled(true);
        }
    }//GEN-LAST:event_cmdSumaActionPerformed

    private void cmdRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRestaActionPerformed
        for (int i = 0; i < v.length; i++) {
            r[i]=v[i]-v1[i];
            txtVectorR.append(r[i]+"\n");
            txtVectorR.append(r[i]+"\n");
            cmdCrear.setEnabled(false);
            cmdAuto.setEnabled(false);
            cmdLlenar.setEnabled(false);
            cmdMostrar.setEnabled(true);
            cmdReset.setEnabled(true);
            
        }
    }//GEN-LAST:event_cmdRestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Punto3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Punto3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAuto;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenar;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdReset;
    private javax.swing.JButton cmdResta;
    private javax.swing.JButton cmdSuma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtLongitud;
    private javax.swing.JTextArea txtVector;
    private javax.swing.JTextArea txtVector1;
    private javax.swing.JTextArea txtVectorR;
    // End of variables declaration//GEN-END:variables
}
